#include <betacalendars/calendar_layout.hpp>

#include <array>
#include <cmath>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <map>
#include <sstream>
#include <stdexcept>
#include <string>

using namespace betacalendars::calendar_layout;
namespace {
using args=std::map<std::string,std::string>;
constexpr std::array<const char*,7> days{"Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"};
constexpr std::array<const char*,12> months{"January","February","March","April","May","June","July","August","September","October","November","December"};
args parse(int argc,char**argv){args a;for(int i=2;i<argc;++i){std::string k=argv[i];if(k=="--help"||k=="-h")return{{"help","1"}};if(k.rfind("--",0)!=0||i+1>=argc||std::string(argv[i+1]).rfind("--",0)==0)throw std::invalid_argument("expected --option value near "+k);a[k.substr(2)]=argv[++i];}return a;}
std::string get(const args&a,const std::string&k,const std::string&d){auto i=a.find(k);return i==a.end()?d:i->second;}
int integer(const args&a,const std::string&k,int d){auto i=a.find(k);if(i==a.end())return d;std::size_t n=0;int v=std::stoi(i->second,&n);if(n!=i->second.size())throw std::invalid_argument("invalid integer for --"+k);return v;}
double real(const args&a,const std::string&k,double d){auto i=a.find(k);if(i==a.end())return d;std::size_t n=0;double v=std::stod(i->second,&n);if(n!=i->second.size()||!std::isfinite(v))throw std::invalid_argument("invalid number for --"+k);return v;}
template<class T>T select(const std::map<std::string,T>&values,const std::string&name,const std::string&option){auto i=values.find(name);if(i==values.end())throw std::invalid_argument("invalid --"+option+" value: "+name);return i->second;}
week_start get_week(const args&a){static const std::map<std::string,week_start> v{{"monday",week_start::monday},{"tuesday",week_start::tuesday},{"wednesday",week_start::wednesday},{"thursday",week_start::thursday},{"friday",week_start::friday},{"saturday",week_start::saturday},{"sunday",week_start::sunday}};return select(v,get(a,"week-start","monday"),"week-start");}
paper_size get_paper(const args&a){static const std::map<std::string,paper_size>v{{"a4",paper_size::a4},{"a5",paper_size::a5},{"letter",paper_size::us_letter},{"us-letter",paper_size::us_letter},{"legal",paper_size::us_legal},{"us-legal",paper_size::us_legal}};return select(v,get(a,"paper","a4"),"paper");}
orientation get_orientation(const args&a){static const std::map<std::string,orientation>v{{"portrait",orientation::portrait},{"landscape",orientation::landscape}};return select(v,get(a,"orientation","portrait"),"orientation");}
grid_mode get_grid(const args&a){static const std::map<std::string,grid_mode>v{{"natural",grid_mode::natural},{"fixed",grid_mode::fixed_six_weeks},{"fixed-6x7",grid_mode::fixed_six_weeks}};return select(v,get(a,"grid","natural"),"grid");}
std::string format(const args&a){const auto f=get(a,"format","text");if(f!="text"&&f!="json"&&f!="csv"&&f!="svg")throw std::invalid_argument("--format must be text, json, csv, or svg");return f;}
std::string q(const std::string&s){return"\""+s+"\"";}
std::string rel(cell_relation r){switch(r){case cell_relation::previous_month:return"previous_month";case cell_relation::current_month:return"current_month";case cell_relation::next_month:return"next_month";case cell_relation::empty:return"empty";}return"empty";}
std::string paper_str(paper_size p){switch(p){case paper_size::a4:return"A4";case paper_size::a5:return"A5";case paper_size::us_letter:return"US Letter";case paper_size::us_legal:return"US Legal";case paper_size::custom:return"Custom";}return"Unknown";}
std::string orient_str(orientation o){return o==orientation::portrait?"portrait":"landscape";}
std::string num(double n){std::ostringstream o;o<<std::fixed<<std::setprecision(2)<<n;return o.str();}
layout_spec make_spec(const args&a,int rows=5,int cols=7){layout_spec s;s.paper=get_paper(a);s.page_orientation=get_orientation(a);const double x=real(a,"margin",10);s.margins={x,x,x,x};s.title_height=real(a,"header",16);s.weekday_header_height=real(a,"weekday-header",8);s.notes_height=real(a,"notes",0);s.rows=rows;s.columns=cols;return s;}
layout_metrics metrics(const args&a,int rows=5,int cols=7){const int pad=integer(a,"cell-padding",2);auto r=measure(make_spec(a,rows,cols),pad);if(!r)throw std::invalid_argument("invalid page geometry (layout error "+std::to_string(static_cast<int>(r.error()))+")");return r.value();}
std::string metrics_json(const layout_metrics&m,const args&a){return"{\"page_width_mm\":"+num(m.page_width_mm)+",\"page_height_mm\":"+num(m.page_height_mm)+",\"margin_mm\":"+num(real(a,"margin",10))+",\"printable_width_mm\":"+num(m.printable_width_mm)+",\"printable_height_mm\":"+num(m.printable_height_mm)+",\"header_mm\":"+num(real(a,"header",16))+",\"weekday_header_mm\":"+num(real(a,"weekday-header",8))+",\"notes_mm\":"+num(real(a,"notes",0))+",\"grid_width_mm\":"+num(m.grid_width_mm)+",\"grid_height_mm\":"+num(m.grid_height_mm)+",\"cell_width_mm\":"+num(m.cell_width_mm)+",\"cell_height_mm\":"+num(m.cell_height_mm)+",\"cell_area_mm2\":"+num(m.cell_area_mm2)+",\"writing_area_mm2\":"+num(m.usable_writing_area_mm2)+"}";}
void emit(const args&a,const std::string&s){auto p=get(a,"output","");if(p.empty())std::cout<<s;else{std::ofstream f(p);if(!f)throw std::runtime_error("cannot write "+p);f<<s;}}
std::string month_json(int y,int m,week_start ws,grid_mode mode){auto g=month_grid(y,m,ws,mode,adjacent_policy::include_adjacent_dates);if(!g)throw std::invalid_argument("invalid date");const int rows=mode==grid_mode::natural?topology(y,m,ws).natural_rows:6;std::ostringstream o;o<<"{\"year\":"<<y<<",\"month\":"<<m<<",\"week_start\":"<<q(days[static_cast<int>(ws)])<<",\"grid\":"<<q(mode==grid_mode::natural?"natural":"fixed-6x7")<<",\"rows\":"<<rows<<",\"cells\":[";bool first=true;for(const auto&c:g.value()){if(!first)o<<',';first=false;o<<"{\"row\":"<<c.row+1<<",\"column\":"<<c.column+1<<",\"weekday\":"<<q(days[static_cast<int>(c.day_of_week)])<<",\"relation\":"<<q(rel(c.relation))<<",\"date\":";if(c.date)o<<"{\"year\":"<<c.date->year<<",\"month\":"<<c.date->month<<",\"day\":"<<c.date->day<<'}';else o<<"null";o<<'}';}o<<"]}";return o.str();}
std::string month_csv(int y,int m,week_start ws,grid_mode mode){auto g=month_grid(y,m,ws,mode,adjacent_policy::include_adjacent_dates);if(!g)throw std::invalid_argument("invalid date");std::ostringstream o;o<<"row,column,weekday,year,month,day,relation\n";for(const auto&c:g.value()){o<<c.row+1<<','<<c.column+1<<','<<days[static_cast<int>(c.day_of_week)]<<',';if(c.date)o<<c.date->year<<','<<c.date->month<<','<<c.date->day;else o<<",,";o<<','<<rel(c.relation)<<'\n';}return o.str();}
std::string month_text(int y,int m,week_start ws,grid_mode mode){auto g=month_grid(y,m,ws,mode,adjacent_policy::include_adjacent_dates);if(!g)throw std::invalid_argument("invalid date");std::ostringstream o;const int rows=mode==grid_mode::natural?topology(y,m,ws).natural_rows:6;o<<months[m-1]<<' '<<y<<" - "<<(mode==grid_mode::natural?"natural":"fixed 6x7")<<" grid; "<<rows<<" rows; week starts "<<days[static_cast<int>(ws)]<<"\n";for(const auto&c:g.value()){if(c.column==0)o<<'\n';if(c.date&&c.relation==cell_relation::current_month)o<<std::setw(2)<<c.date->day;else o<<"  ";if(c.column<6)o<<' ';}return o.str()+"\n";}
std::string svg(const args&a,int y,int m,week_start ws,grid_mode mode,bool blank,int blank_rows){const int rows=blank?blank_rows:(mode==grid_mode::natural?topology(y,m,ws).natural_rows:6);auto met=metrics(a,rows);const double x=(met.page_width_mm-met.printable_width_mm)/2;const double yy=(met.page_height_mm-met.printable_height_mm)/2+real(a,"header",16)+real(a,"weekday-header",8);std::ostringstream o;o<<"<svg xmlns=\"http://www.w3.org/2000/svg\" width=\""<<num(met.page_width_mm)<<"mm\" height=\""<<num(met.page_height_mm)<<"mm\" viewBox=\"0 0 "<<num(met.page_width_mm)<<' '<<num(met.page_height_mm)<<"\">\n<rect width=\"100%\" height=\"100%\" fill=\"white\"/>\n";if(!blank)o<<"<text x=\""<<num(x)<<"\" y=\""<<num(yy-real(a,"weekday-header",8)-4)<<"\" font-family=\"sans-serif\" font-size=\"6\" font-weight=\"bold\">"<<months[m-1]<<' '<<y<<"</text>\n";for(int c=0;c<7;++c)o<<"<text x=\""<<num(x+(c+.5)*met.cell_width_mm)<<"\" y=\""<<num(yy-2)<<"\" text-anchor=\"middle\" font-family=\"sans-serif\" font-size=\"3.5\">"<<days[(static_cast<int>(ws)+c)%7]<<"</text>\n";for(int r=0;r<rows;++r)for(int c=0;c<7;++c){const double xx=x+c*met.cell_width_mm,cy=yy+r*met.cell_height_mm;o<<"<rect x=\""<<num(xx)<<"\" y=\""<<num(cy)<<"\" width=\""<<num(met.cell_width_mm)<<"\" height=\""<<num(met.cell_height_mm)<<"\" fill=\"white\" stroke=\"#64748b\" stroke-width=\"0.25\"/>\n";if(!blank){auto g=month_grid(y,m,ws,mode,adjacent_policy::include_adjacent_dates);const auto&cell=g.value()[static_cast<std::size_t>(r*7+c)];if(cell.date)o<<"<text x=\""<<num(xx+1.5)<<"\" y=\""<<num(cy+4)<<"\" font-family=\"sans-serif\" font-size=\"3.2\" fill=\""<<(cell.relation==cell_relation::current_month?"#111827":"#94a3b8")<<"\">"<<cell.date->day<<"</text>\n";}}o<<"</svg>\n";return o.str();}
std::string usage(){return"Commands: month, year, blank, paper, compare, validate, version\nTry --help after a command. Common options: --format text|json|csv|svg, --output PATH.\n";}
int run(int argc,char**argv){if(argc<2){std::cout<<usage();return 0;}const std::string cmd=argv[1];if(cmd=="version"||cmd=="--version"){std::cout<<"betacal-layout 0.1.0\n";return 0;}if(cmd=="help"||cmd=="--help"||cmd=="-h"){std::cout<<usage();return 0;}const auto a=parse(argc,argv);if(a.count("help")){std::cout<<usage();return 0;}const auto f=format(a);
 if(cmd=="month"){int y=integer(a,"year",2027),m=integer(a,"month",1);if(y<1||y>9999||m<1||m>12)throw std::invalid_argument("year must be 1..9999; month 1..12");auto ws=get_week(a);auto mode=get_grid(a);std::string out=f=="json"?month_json(y,m,ws,mode)+"\n":f=="csv"?month_csv(y,m,ws,mode):f=="svg"?svg(a,y,m,ws,mode,false,0):month_text(y,m,ws,mode);emit(a,out);return 0;}
 if(cmd=="year"){int y=integer(a,"year",2027);if(y<1||y>9999)throw std::invalid_argument("year must be 1..9999");if(f=="svg")throw std::invalid_argument("year SVG is unavailable; request a month SVG");auto ws=get_week(a);std::ostringstream o;if(f=="json")o<<"{\"year\":"<<y<<",\"days\":"<<(is_leap_year(y)?366:365)<<",\"months\":[";else if(f=="csv")o<<"year,month,days,first_weekday,week_start,offset,natural_rows\n";else o<<y<<" ("<<(is_leap_year(y)?366:365)<<" days)\n";for(int m=1;m<=12;++m){auto t=topology(y,m,ws);if(f=="json"){if(m>1)o<<',';o<<"{\"month\":"<<m<<",\"days\":"<<t.days<<",\"first_weekday\":"<<q(days[static_cast<int>(t.first_weekday)])<<",\"offset\":"<<t.leading_cells<<",\"natural_rows\":"<<t.natural_rows<<'}';}else if(f=="csv")o<<y<<','<<m<<','<<t.days<<','<<days[static_cast<int>(t.first_weekday)]<<','<<days[static_cast<int>(ws)]<<','<<t.leading_cells<<','<<t.natural_rows<<'\n';else o<<months[m-1]<<": "<<t.days<<" days; begins "<<days[static_cast<int>(t.first_weekday)]<<"; "<<t.natural_rows<<" rows\n";}if(f=="json")o<<"]}";emit(a,o.str()+"\n");return 0;}
 if(cmd=="blank"){int rows=integer(a,"rows",6);if(rows!=5&&rows!=6)throw std::invalid_argument("blank grids support 5 or 6 rows");auto ws=get_week(a);auto m=metrics(a,rows);std::string out;if(f=="svg")out=svg(a,0,1,ws,grid_mode::natural,true,rows);else if(f=="json")out="{\"rows\":"+std::to_string(rows)+",\"columns\":7,\"week_start\":"+q(days[static_cast<int>(ws)])+",\"cells\":"+std::to_string(rows*7)+",\"dated\":false,\"metrics\":"+metrics_json(m,a)+"}\n";else if(f=="csv"){std::ostringstream o;o<<"row,column,weekday,dated\n";for(int r=1;r<=rows;++r)for(int c=0;c<7;++c)o<<r<<','<<c+1<<','<<days[(static_cast<int>(ws)+c)%7]<<",false\n";out=o.str();}else out="Undated grid: "+std::to_string(rows)+" x 7; "+days[static_cast<int>(ws)]+" first\n"+metrics_json(m,a)+"\n";emit(a,out);return 0;}
 if(cmd=="paper"){if(f=="svg")throw std::invalid_argument("paper SVG is unavailable; use blank --format svg");auto m=metrics(a,integer(a,"rows",6));if(f=="json")emit(a,metrics_json(m,a)+"\n");else if(f=="csv")emit(a,"metric,value_mm\npage_width,"+num(m.page_width_mm)+"\npage_height,"+num(m.page_height_mm)+"\nprintable_width,"+num(m.printable_width_mm)+"\nprintable_height,"+num(m.printable_height_mm)+"\ngrid_width,"+num(m.grid_width_mm)+"\ngrid_height,"+num(m.grid_height_mm)+"\ncell_width,"+num(m.cell_width_mm)+"\ncell_height,"+num(m.cell_height_mm)+"\ncell_area,"+num(m.cell_area_mm2)+"\nwriting_area,"+num(m.usable_writing_area_mm2)+"\n");else emit(a,paper_str(get_paper(a))+" "+orient_str(get_orientation(a))+"\n"+metrics_json(m,a)+"\n");return 0;}
 if(cmd=="compare"){if(f=="svg")throw std::invalid_argument("compare SVG is unavailable");const paper_size ps[]{paper_size::a4,paper_size::a5,paper_size::us_letter,paper_size::us_legal};const orientation os[]{orientation::portrait,orientation::landscape};std::ostringstream o;bool first=true;if(f=="json")o<<'[';if(f=="csv")o<<"paper,orientation,page_width_mm,page_height_mm,printable_width_mm,printable_height_mm,cell_width_mm,cell_height_mm\n";for(auto p:ps)for(auto ori:os){args b=a;b["paper"]=p==paper_size::a4?"a4":p==paper_size::a5?"a5":p==paper_size::us_letter?"letter":"legal";b["orientation"]=orient_str(ori);auto m=metrics(b,integer(a,"rows",6));if(f=="json"){if(!first)o<<',';first=false;o<<"{\"paper\":"<<q(paper_str(p))<<",\"orientation\":"<<q(orient_str(ori))<<",\"metrics\":"<<metrics_json(m,b)<<'}';}else if(f=="csv")o<<b["paper"]<<','<<orient_str(ori)<<','<<num(m.page_width_mm)<<','<<num(m.page_height_mm)<<','<<num(m.printable_width_mm)<<','<<num(m.printable_height_mm)<<','<<num(m.cell_width_mm)<<','<<num(m.cell_height_mm)<<'\n';else o<<paper_str(p)<<' '<<orient_str(ori)<<": "<<metrics_json(m,b)<<'\n';}if(f=="json")o<<"]\n";emit(a,o.str());return 0;}
 if(cmd=="validate"){if(f=="svg")throw std::invalid_argument("validation does not have SVG output");int from=integer(a,"from-year",1900),to=integer(a,"to-year",2100);if(from<1||to>9999||from>to)throw std::invalid_argument("year range must be ordered and within 1..9999");long long checked=0;for(int y=from;y<=to;++y)for(int m=1;m<=12;++m)for(int s=0;s<7;++s){auto n=month_grid(y,m,static_cast<week_start>(s),grid_mode::natural);auto fixed=month_grid(y,m,static_cast<week_start>(s),grid_mode::fixed_six_weeks);int count=0;if(!n||!fixed||n.value().size()<28||n.value().size()>42||n.value().size()%7||fixed.value().size()!=42)throw std::runtime_error("grid size invariant failed");for(const auto&c:n.value())if(c.relation==cell_relation::current_month)++count;if(count!=days_in_month(y,m))throw std::runtime_error("date completeness failed");++checked;}if(f=="json")emit(a,"{\"status\":\"PASS\",\"from_year\":"+std::to_string(from)+",\"to_year\":"+std::to_string(to)+",\"year_month_week_start_combinations\":"+std::to_string(checked)+",\"grid_modes\":2}\n");else if(f=="csv")emit(a,"status,from_year,to_year,combinations,modes\nPASS,"+std::to_string(from)+','+std::to_string(to)+','+std::to_string(checked)+",2\n");else emit(a,"PASS: "+std::to_string(checked)+" year-month-week-start combinations; natural and fixed grids; "+std::to_string(from)+".."+std::to_string(to)+"\n");return 0;}
 throw std::invalid_argument("unknown command: "+cmd);}
}
int main(int argc,char**argv){try{return run(argc,argv);}catch(const std::exception&e){std::cerr<<"betacal-layout: "<<e.what()<<'\n';return 2;}}
